const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    ME: "/auth/me",
    REFRESH_TOKEN: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_EMAIL: "/auth/verify-email",
    CHANGE_PASSWORD: "/auth/change-password",
    PROFILE: "/auth/profile",
    AVATAR: "/auth/avatar",
    ACCOUNT: "/auth/account",
  },
  USERS: {
    PROFILE: "/users/profile",
    ALL: "/users",
    DETAILS: (id) => `/users/${id}`,
  },
  PATIENTS: {
    ALL: "/patients",
    DETAILS: (id) => `/patients/${id}`,
    DASHBOARD: "/patients/dashboard",
    PROFILE: "/patients/profile",
    SEARCH: "/patients/search",
  },
  DOCTORS: {
    ALL: "/doctors",
    DETAILS: (id) => `/doctors/${id}`,
    DASHBOARD: "/doctors/dashboard",
    AVAILABLE: "/doctors/available",
    SEARCH: "/doctors/search",
    PROFILE: "/doctors/profile",
  },
  APPOINTMENTS: {
    ALL: "/appointments",
    CREATE: "/appointments",
    DETAILS: (id) => `/appointments/${id}`,
    UPDATE: (id) => `/appointments/${id}`,
    DELETE: (id) => `/appointments/${id}`,
    UPCOMING: "/appointments/upcoming",
    TODAY: "/appointments/today",
    CANCEL: (id) => `/appointments/${id}/cancel`,
    COMPLETE: (id) => `/appointments/${id}/complete`,
    CONFIRM: (id) => `/appointments/${id}/confirm`,
    RESCHEDULE: (id) => `/appointments/${id}/reschedule`,
    NOTES: (id) => `/appointments/${id}/notes`,
  },
  REPORTS: {
    ALL: "/reports",
    CREATE: "/reports",
    DETAILS: (id) => `/reports/${id}`,
    UPDATE: (id) => `/reports/${id}`,
    DELETE: (id) => `/reports/${id}`,
    SEARCH: "/reports/search",
  },
  PRESCRIPTIONS: {
    ALL: "/prescriptions",
    CREATE: "/prescriptions",
    DETAILS: (id) => `/prescriptions/${id}`,
    UPDATE: (id) => `/prescriptions/${id}`,
    DELETE: (id) => `/prescriptions/${id}`,
    SEARCH: "/prescriptions/search",
  },
  AI: {
    CHAT: "/ai/chat",
    ASK: "/ai/ask",
    SYMPTOMS: "/ai/symptoms",
    MEDICINE_ADVICE: "/ai/medicine",
    HEALTH_TIPS: "/ai/health-tips",
    SUMMARIZE_REPORT: (id) => `/ai/report/${id}/summary`,
    HEALTH_SCORE: (id) => `/ai/report/${id}/health-score`,
  },
  NOTIFICATIONS: {
    ALL: "/notifications",
    READ: (id) => `/notifications/${id}/read`,
    READ_ALL: "/notifications/read-all",
    UNREAD_COUNT: "/notifications/unread-count",
  },
  UPLOADS: {
    FILE: "/upload",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    STATISTICS: "/admin/statistics",
    USERS: "/admin/users",
    DOCTORS: "/admin/doctors",
    REPORTS: "/admin/reports",
    PRESCRIPTIONS: "/admin/prescriptions",
    BROADCAST: "/admin/broadcast",
  },
};

export default ENDPOINTS;
