const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    ME: "/auth/me",
    REFRESH_TOKEN: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_EMAIL: "/auth/verify-email",
    CHANGE_PASSWORD: "/auth/change-password",
    PROFILE: "/auth/profile",
    AVATAR: "/auth/avatar",
    ACCOUNT: "/auth/account",
  },
  USERS: {
    PROFILE: "/users/profile",
    ALL: "/users",
    DETAILS: (id) => `/users/${id}`,
  },
  PATIENTS: {
    ALL: "/patients",
    DETAILS: (id) => `/patients/${id}`,
    DASHBOARD: "/patients/dashboard",
    PROFILE: "/patients/profile",
    SEARCH: "/patients/search",
  },
  DOCTORS: {
    ALL: "/doctors",
    DETAILS: (id) => `/doctors/${id}`,
    DASHBOARD: "/doctors/dashboard",
    AVAILABLE: "/doctors/available",
    SEARCH: "/doctors/search",
    PROFILE: "/doctors/profile",
  },
  APPOINTMENTS: {
    ALL: "/appointments",
    CREATE: "/appointments",
    DETAILS: (id) => `/appointments/${id}`,
    UPDATE: (id) => `/appointments/${id}`,
    DELETE: (id) => `/appointments/${id}`,
    UPCOMING: "/appointments/upcoming",
    TODAY: "/appointments/today",
    CANCEL: (id) => `/appointments/${id}/cancel`,
    COMPLETE: (id) => `/appointments/${id}/complete`,
    CONFIRM: (id) => `/appointments/${id}/confirm`,
    RESCHEDULE: (id) => `/appointments/${id}/reschedule`,
    NOTES: (id) => `/appointments/${id}/notes`,
  },
  REPORTS: {
    ALL: "/reports",
    CREATE: "/reports",
    DETAILS: (id) => `/reports/${id}`,
    UPDATE: (id) => `/reports/${id}`,
    DELETE: (id) => `/reports/${id}`,
    SEARCH: "/reports/search",
  },
  PRESCRIPTIONS: {
    ALL: "/prescriptions",
    CREATE: "/prescriptions",
    DETAILS: (id) => `/prescriptions/${id}`,
    UPDATE: (id) => `/prescriptions/${id}`,
    DELETE: (id) => `/prescriptions/${id}`,
    SEARCH: "/prescriptions/search",
  },
  AI: {
    WEBSITE_ASSISTANT: "/ai/website-assistant",
    CHAT: "/ai/chat",
    CHAT_HISTORY: "/ai/chat/history",
    ASK: "/ai/ask",
    SYMPTOMS: "/ai/symptoms",
    MEDICINE_ADVICE: "/ai/medicine",
    HEALTH_SCORE_CALC: "/ai/health-score",
    HEALTH_TIPS: "/ai/health-tips",
    SUMMARIZE_REPORT: (id) => `/ai/report/${id}/summary`,
    HEALTH_SCORE: (id) => `/ai/report/${id}/health-score`,
    CONVERSATIONS: "/ai/conversations",
    CONVERSATION: (id) => `/ai/conversations/${id}`,
    CONVERSATION_CHAT: (id) => `/ai/conversations/${id}/chat`,
    CONVERSATION_STREAM: (id) => `/ai/conversations/${id}/stream`,
    INTERPRET_LAB: "/ai/interpret-lab",
  },
  NOTIFICATIONS: {
    ALL: "/notifications",
    READ: (id) => `/notifications/${id}/read`,
    READ_ALL: "/notifications/read-all",
    UNREAD_COUNT: "/notifications/unread-count",
  },
  UPLOADS: {
    FILE: "/upload",
  },
  ADMIN: {
    LOGIN: "/admin/login",
    DASHBOARD: "/admin/dashboard",
    STATISTICS: "/admin/statistics",
    USERS: "/admin/users",
    DOCTORS: "/admin/doctors",
    REPORTS: "/admin/reports",
    PRESCRIPTIONS: "/admin/prescriptions",
    APPOINTMENTS: "/admin/appointments",
    BROADCAST: "/admin/broadcast",
    AUDIT_LOGS: "/admin/audit-logs",
    AUDIT_STATISTICS: "/admin/audit-logs/statistics",
    APPROVE_DOCTOR: (id) => `/admin/doctors/${id}/approve`,
    REJECT_DOCTOR: (id) => `/admin/doctors/${id}/reject`,
  },
  CONSULTATIONS: {
    CREATE: "/consultations",
    DETAILS: (id) => `/consultations/${id}`,
    UPDATE: (id) => `/consultations/${id}`,
    DELETE: (id) => `/consultations/${id}`,
    BY_APPOINTMENT: (appointmentId) => `/consultations/appointment/${appointmentId}`,
    BY_DOCTOR: (doctorId) => `/consultations/doctor/${doctorId}`,
    BY_PATIENT: (patientId) => `/consultations/patient/${patientId}`,
  },
  PRESCRIPTION_TEMPLATES: {
    CREATE: "/prescription-templates",
    MY: "/prescription-templates/my",
    DETAILS: (id) => `/prescription-templates/${id}`,
    UPDATE: (id) => `/prescription-templates/${id}`,
    DELETE: (id) => `/prescription-templates/${id}`,
    FAVORITE: (id) => `/prescription-templates/${id}/favorite`,
    USE: (id) => `/prescription-templates/${id}/use`,
  },
};

export default ENDPOINTS;
